// Copyright (C) 2026 Trevor Vaughan
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

package ca

import (
	"bytes"
	"crypto"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"log/slog"
	"math/big"
	"os"
	"time"

	"github.com/tvaughan/puppet-ca/internal/storage"
)

func (c *CA) Init() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if err := c.Storage.EnsureDirs(); err != nil {
		return err
	}

	// Try loading existing CA first.
	if err := c.loadCA(); err == nil {
		slog.Info("Loaded existing CA", "cert", c.Storage.CACertPath())
		if err := c.buildSerialIndex(); err != nil {
			slog.Warn("Failed to build OCSP serial index", "error", err)
		}
		return nil
	}

	_, errCert := os.Stat(c.Storage.CACertPath())
	_, errKey := os.Stat(c.Storage.CAKeyPath())

	if os.IsNotExist(errCert) || os.IsNotExist(errKey) {
		slog.Info("No existing CA found, bootstrapping new CA")
		return c.bootstrapCA()
	}

	return fmt.Errorf("failed to load existing CA: files exist but could not be parsed")
}

// loadCA reads and validates the CA key and certificate from disk.
// It accepts RSA keys (PKCS1 and PKCS8) and ECDSA keys (SEC1 and PKCS8),
// and verifies that the private key matches the certificate's public key.
func (c *CA) loadCA() error {
	keyPEM, err := os.ReadFile(c.Storage.CAKeyPath())
	if err != nil {
		return err
	}
	block, _ := pem.Decode(keyPEM)
	if block == nil {
		return fmt.Errorf("failed to decode CA key PEM")
	}

	var key crypto.Signer
	switch block.Type {
	case "RSA PRIVATE KEY":
		k, err := x509.ParsePKCS1PrivateKey(block.Bytes)
		if err != nil {
			return fmt.Errorf("failed to parse RSA PKCS1 private key: %w", err)
		}
		key = k
	case "EC PRIVATE KEY":
		k, err := x509.ParseECPrivateKey(block.Bytes)
		if err != nil {
			return fmt.Errorf("failed to parse EC private key: %w", err)
		}
		key = k
	case "PRIVATE KEY":
		k, err := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err != nil {
			return fmt.Errorf("failed to parse PKCS8 private key: %w", err)
		}
		signer, ok := k.(crypto.Signer)
		if !ok {
			return fmt.Errorf("PKCS8 private key does not implement crypto.Signer")
		}
		key = signer
	default:
		// Try PKCS1 and PKCS8 regardless of header for maximum compatibility
		// with keys generated by external tools.
		if k1, err1 := x509.ParsePKCS1PrivateKey(block.Bytes); err1 == nil {
			key = k1
		} else if k8, err8 := x509.ParsePKCS8PrivateKey(block.Bytes); err8 == nil {
			signer, ok := k8.(crypto.Signer)
			if !ok {
				return fmt.Errorf("PKCS8 private key does not implement crypto.Signer")
			}
			key = signer
		} else {
			return fmt.Errorf("unrecognized PEM type %q (PKCS1: %v; PKCS8: %v)", block.Type, err1, err8)
		}
	}

	certPEM, err := os.ReadFile(c.Storage.CACertPath())
	if err != nil {
		return err
	}
	block, _ = pem.Decode(certPEM)
	if block == nil {
		return fmt.Errorf("failed to decode CA cert PEM")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return err
	}

	// Verify that the loaded key matches the certificate's public key.
	certPubDER, err := x509.MarshalPKIXPublicKey(cert.PublicKey)
	if err != nil {
		return fmt.Errorf("failed to marshal cert public key for validation: %w", err)
	}
	keyPubDER, err := x509.MarshalPKIXPublicKey(key.Public())
	if err != nil {
		return fmt.Errorf("failed to marshal loaded key's public key for validation: %w", err)
	}
	if !bytes.Equal(certPubDER, keyPubDER) {
		return fmt.Errorf("CA private key does not match CA certificate's public key")
	}

	c.CAKey = key
	c.CACert = cert
	return nil
}

func (c *CA) bootstrapCA() error {
	hostname := c.Hostname
	if hostname == "" {
		hostname = "puppet"
	}

	// Resolve key config; fall back to default if not set.
	keyCfg := c.CAKeyConfig
	if keyCfg.Algo == "" {
		keyCfg = DefaultCAKeyConfig
	}

	slog.Debug("Generating CA key", "algo", string(keyCfg.Algo), "size", keyCfg.Size)
	key, err := generateKey(keyCfg)
	if err != nil {
		return fmt.Errorf("failed to generate CA key: %w", err)
	}

	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)
	if err != nil {
		return fmt.Errorf("failed to generate serial number: %w", err)
	}

	// SubjectKeyIdentifier: SHA-1 of SubjectPublicKeyInfo DER (RFC 5280 §4.2.1.2).
	subjectKeyID, err := subjectKeyIDFromPublicKey(key.Public())
	if err != nil {
		return fmt.Errorf("failed to compute SubjectKeyIdentifier: %w", err)
	}

	// Build subject DN.
	subject := pkix.Name{
		CommonName: "Puppet CA: " + hostname,
	}
	if c.CASubject.Org != "" {
		subject.Organization = []string{c.CASubject.Org}
	}
	if c.CASubject.OrgUnit != "" {
		subject.OrganizationalUnit = []string{c.CASubject.OrgUnit}
	}
	if c.CASubject.Country != "" {
		subject.Country = []string{c.CASubject.Country}
	}
	if c.CASubject.Locality != "" {
		subject.Locality = []string{c.CASubject.Locality}
	}
	if c.CASubject.Province != "" {
		subject.Province = []string{c.CASubject.Province}
	}

	now := time.Now().UTC()

	caValidity := certValidity
	if c.CAValidityDays > 0 {
		caValidity = time.Duration(c.CAValidityDays) * 24 * time.Hour
	}

	template := &x509.Certificate{
		SerialNumber:          serialNumber,
		Subject:               subject,
		NotBefore:             now.Add(-24 * time.Hour),
		NotAfter:              now.Add(caValidity),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
		SubjectKeyId:          subjectKeyID,
	}

	// Apply pathLenConstraint when CAPathLength >= 0.
	// -1 (the default) means unconstrained: leave MaxPathLen/MaxPathLenZero at
	// their zero values, which Go's x509 package interprets as "no constraint".
	if c.CAPathLength >= 0 {
		template.MaxPathLen = c.CAPathLength
		template.MaxPathLenZero = (c.CAPathLength == 0)
	}

	certBytes, err := x509.CreateCertificate(rand.Reader, template, template, key.Public(), key)
	if err != nil {
		return fmt.Errorf("failed to create CA cert: %w", err)
	}

	parsedCert, err := x509.ParseCertificate(certBytes)
	if err != nil {
		return fmt.Errorf("failed to parse generated CA cert: %w", err)
	}
	c.CAKey = key
	c.CACert = parsedCert

	// Save private key (mode 0640).
	keyPEM, err := marshalPrivateKeyPEM(key)
	if err != nil {
		return fmt.Errorf("failed to marshal CA key: %w", err)
	}
	if err := os.WriteFile(c.Storage.CAKeyPath(), keyPEM, storage.FilePermPrivate); err != nil {
		return fmt.Errorf("failed to write CA key: %w", err)
	}

	// Save CA cert (mode 0644).
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certBytes})
	if err := os.WriteFile(c.Storage.CACertPath(), certPEM, storage.FilePermPublic); err != nil {
		return fmt.Errorf("failed to write CA cert: %w", err)
	}

	// Write a public key file alongside the cert.
	pubKeyBytes, err := x509.MarshalPKIXPublicKey(key.Public())
	if err == nil {
		pubKeyPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubKeyBytes})
		_ = os.WriteFile(c.Storage.CAPubKeyPath(), pubKeyPEM, storage.FilePermPublic)
	}

	// Generate empty CRL.
	crlTemplate := &x509.RevocationList{
		Number:     big.NewInt(1),
		ThisUpdate: now,
		NextUpdate: now.Add(c.crlValidity()),
	}
	crlBytes, err := x509.CreateRevocationList(rand.Reader, crlTemplate, c.CACert, c.CAKey)
	if err != nil {
		return fmt.Errorf("failed to create initial CRL: %w", err)
	}
	crlPEM := pem.EncodeToMemory(&pem.Block{Type: "X509 CRL", Bytes: crlBytes})
	if err := c.Storage.UpdateCRL(crlPEM); err != nil {
		return fmt.Errorf("failed to write initial CRL: %w", err)
	}

	// Touch inventory.
	f, err := os.OpenFile(c.Storage.InventoryPath(), os.O_CREATE|os.O_RDONLY, storage.FilePermPublic)
	if err != nil {
		return fmt.Errorf("failed to create inventory: %w", err)
	}
	f.Close()

	slog.Info("CA bootstrapped",
		"cn", template.Subject.CommonName,
		"algo", string(keyCfg.Algo),
		"size", keyCfg.Size,
		"cadir", c.Storage.CADir(),
	)
	return nil
}
