{{- if .Values.ingress.enabled }}
{{- $backend := ternary "metrics" "https" (eq .Values.ingress.backendPort "metrics") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openvox-ca.fullname" . }}
  namespace: {{ include "openvox-ca.namespace" . }}
  labels:
    {{- include "openvox-ca.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.ingress.annotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "openvox-ca.fullname" $ }}
                port:
                  name: {{ $backend }}
          {{- end }}
    {{- end }}
{{- end }}
